pred_dir   = ~/cafa/prediction/bpo/
prev_dir   = ~/cafa/seq-centric/bpo/
eval_dir   = ~/cafa/evaluation/
ont_term   = ~/cafa/ontology/bpo_term.txt
annotation = ~/cafa/benchmark/groundtruth/bpoa.mat
benchmark  = ~/cafa/benchmark/lists/bpo_hard_type1.txt
bootstrap  = ~/cafa/config/bootstrap/bpo_hard_type1.mat

ontology = bpo
category = hard
type = 1
mode = 1

metric = f
metric = wf
metric = s
metric = ns
metric = auc

model = all
model = +BN1S
model = +BB1S
model = +BN4S
model = +BB4S
