pred_dir   = ~/cafa/prediction/bpo/
prev_dir   = ~/cafa/seq-centric/bpo/
eval_dir   = ~/cafa/evaluation/
ont_term   = ~/cafa/ontology/bpo_term.txt
annotation = ~/cafa/benchmark/groundtruth/bpoa.mat
benchmark  = ~/cafa/benchmark/lists/bpo_YEAST_type2.txt
bootstrap  = ~/cafa/config/bootstrap/bpo_YEAST_type2.mat

ontology = bpo
category = YEAST
type = 2
mode = 1

metric = f
metric = wf
metric = s
metric = ns
metric = auc

model = all
model = +BN1S
model = +BB1S
model = +BN4S
model = +BB4S
