pred_dir   = ~/cv3/prediction/bpo/
prev_dir   = ~/cv3/seq-centric/bpo/
eval_dir   = ~/cv3/evaluation/
ont_term   = ~/cv3/ontology/bpo_term.txt
annotation = ~/cv3/benchmark/groundtruth/bpoa.mat
benchmark  = ~/cv3/benchmark/lists/bpo_HUMAN_type2.txt
bootstrap  = ~/cv3/config/bootstrap/bpo_HUMAN_type2.mat

ontology = bpo
category = HUMAN
type = 2
mode = 1

metric = f
metric = wf
metric = s
metric = ns
metric = auc

model = all
model = +BN1S
model = +BB1S
model = +BN4S
model = +BB4S
