pred_dir   = ~/cafa/prediction/cco/
prev_dir   = ~/cafa/seq-centric/cco/
eval_dir   = ~/cafa/evaluation/
ont_term   = ~/cafa/ontology/cco_term.txt
annotation = ~/cafa/benchmark/groundtruth/ccoa.mat
benchmark  = ~/cafa/benchmark/lists/cco_YEAST_type1.txt
bootstrap  = ~/cafa/config/bootstrap/cco_YEAST_type1.mat

ontology = cco
category = YEAST
type = 1
mode = 2

metric = f
metric = wf
metric = s
metric = ns
metric = auc

model = all
model = +BN1S
model = +BB1S
model = +BN4S
model = +BB4S
