pred_dir   = ~/cafa/prediction/hpo/
prev_dir   = ~/cafa/seq-centric/hpo/
eval_dir   = ~/cafa/evaluation/
ont_term   = ~/cafa/ontology/hpo_term.txt
annotation = ~/cafa/benchmark/groundtruth/hpoa.mat
benchmark  = ~/cafa/benchmark/lists/hpo_HUMAN_type1.txt
bootstrap  = ~/cafa/config/bootstrap/hpo_HUMAN_type1.mat

ontology = hpo
category = HUMAN
type = 1
mode = 2

metric = f
metric = wf
metric = s
metric = ns
metric = auc

model = all
model = +BN4H
model = +BB4H
