pred_dir   = ~/cafa/prediction/mfo/
prev_dir   = ~/cafa/seq-centric/mfo/
eval_dir   = ~/cafa/evaluation/
ont_term   = ~/cafa/ontology/mfo_term.txt
annotation = ~/cafa/benchmark/groundtruth/mfoa.mat
benchmark  = ~/cafa/benchmark/lists/mfo_eukarya_type2.txt
bootstrap  = ~/cafa/config/bootstrap/mfo_eukarya_type2.mat

ontology = mfo
category = eukarya
type = 2
mode = 2

metric = f
metric = wf
metric = s
metric = ns
metric = auc

model = all
model = +BN1S
model = +BB1S
model = +BN4S
model = +BB4S
