pred_dir = ~/cafa/prediction/bpo/
prev_dir = ~/cafa/seq-centric/bpo/
annotation = ~/cafa/benchmark/groundtruth/bpoa.mat
benchmark = ~/cafa/benchmark/lists/bpo_all_type1.txt

ontology = bpo
category = all

metric = f
metric = wf
metric = s
metric = ns

model = all
model = +BN1S
model = +BB1S
model = +BN4S
model = +BB4S

# -------------
# Yuxiang Jiang (yuxjiang@indiana.edu)
# Department of Computer Science
# Indiana University, Bloomington
# Last modified: Mon 07 Mar 2016 12:05:48 AM E
