pred_dir = ~/cafa/prediction/hpo/
prev_dir = ~/cafa/seq-centric/hpo/
annotation = ~/cafa/benchmark/groundtruth/hpoa.mat
benchmark = ~/cafa/benchmark/lists/hpo_HUMAN_type1.txt

ontology = hpo
category = HUMAN

metric = f
metric = wf
metric = s
metric = ns

model = all
model = +BN4H
model = +BB4H

# -------------
# Yuxiang Jiang (yuxjiang@indiana.edu)
# Department of Computer Science
# Indiana University, Bloomington
# Last modified: Mon 07 Mar 2016 12:06:29 AM E
