pred_dir = ~/cafa/duel/cafa2/prediction/bpo/
prev_dir = ~/cafa/duel/cafa2/seq-centric/bpo/
annotation = ~/cafa/duel/cafa2/benchmark/groundtruth/bpoa.mat
benchmark = ~/cafa/duel/cafa2/benchmark/lists/bpo_all_type1.txt

ontology = bpo
category = all

metric = f

model = all

# -------------
# Yuxiang Jiang (yuxjiang@indiana.edu)
# Department of Computer Science
# Indiana University, Bloomington
# Last modified: Mon 07 Mar 2016 12:12:16 AM E
