pred_dir = ~/cafa/prediction/cco/
prev_dir = ~/cafa/seq-centric/cco/
annotation = ~/cafa/benchmark/groundtruth/ccoa.mat
benchmark = ~/cafa/benchmark/lists/cco_all_typex.txt

ontology = cco
category = all

metric = f
metric = wf
metric = s
metric = ns

model = all
model = +BN1S
model = +BB1S
model = +BN4S
model = +BB4S

# -------------
# Yuxiang Jiang (yuxjiang@indiana.edu)
# Department of Computer Science
# Indiana University, Bloomington
# Last modified: Wed 04 Apr 2018 08:08:05 PM E
